apiVersion: v1
kind: Service
metadata:
  name: zorix-agent-service
  namespace: zorix-agent
  labels:
    app: zorix-agent
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: zorix-agent
---
apiVersion: v1
kind: Service
metadata:
  name: zorix-agent-nodeport
  namespace: zorix-agent
  labels:
    app: zorix-agent
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800
    protocol: TCP
    name: http
  selector:
    app: zorix-agent